name: sfml-prebuilt-actions-workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: git clone SFML
        run: git clone https://github.com/SFML/SFML.git

      - name: cmake SFML
        shell: cmd
        run: cd SFML && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="%~dp0build/sfml"  -B./build
      
      - name: cd build
        run: cd build
        
      - name: mingw build
        shell: cmd
        run: mingw32-make install
