name: sfml-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: git clone SFML
        run: git clone --branch 2.5.1 https://github.com/SFML/SFML.git

      - name: cmake SFML
        shell: cmd
        run: cd SFML && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DSFML_USE_SYSTEM_DEPS=FALSE -DOPENGL_ES=TRUE -DCMAKE_INSTALL_PREFIX="build/sfml" -B./build
      
      - name: mingw build 
        shell: cmd
        run: cd SFML\build && mingw32-make install
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SFML/build"
          name: "$GITHUB_REF_NAME-mingw"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

          
          
          
          
          
          
        
        
