name: sfml-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      mingwTargetZip: sfml-${{ env.GITHUB_REF_NAME }}-mingw.zip
    steps:
      - name: git clone SFML
        run: git clone --branch 2.5.1 https://github.com/SFML/SFML.git

      - name: cmake SFML
        shell: cmd
        run: cd SFML && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DSFML_USE_SYSTEM_DEPS=FALSE -DOPENGL_ES=TRUE -DCMAKE_INSTALL_PREFIX="build/sfml" -B./build
      
      - name: mingw build 
        shell: cmd
        run: cd SFML\build && mingw32-make install
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: "SFML/build"
          filename: "${{ env.mingwTargetZip }}"
          exclusions: '*.git* /*node_modules/* .editorconfig'
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

          
          
          
          
          
          
        
        
