name: sfml-prebuilt-actions-workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: git clone SFML
        run: git clone --branch 2.5.1 https://github.com/SFML/SFML.git

      - name: cmake SFML
        shell: cmd
        run: cd SFML && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DSFML_USE_SYSTEM_DEPS=FALSE -DOPENGL_ES=TRUE -DCMAKE_INSTALL_PREFIX="build/sfml" -B./build
      
      - name: mingw build 
        shell: cmd
        run: cd SFML\build && mingw32-make install
        
      - name: release prebuilt
        uses: actions/upload-artifact@v2
        with:
          name: SFML-prebuilt
          path: SFML\build

        
